# Basic Site Info
title: Gold Backed News
description: "Information is currency"
author: Gold Backed News

# Site Flag
flag:
  show: true
  path: /assets/GBNname.png

# Comments
disqus:
  enabled: true
  shortname: gold-backed-news

# Analytics
google_analytics: G-LVVZX57YYK

# Ads
adsense:
  enabled: true
  data-ad-client: ca-pub-  #REPLACEME

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/
  staff:
    output: true
    permalink: /about/staff/:title

# Build settings
markdown: kramdown
remote_theme: morpheus636/jekyll-news
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
future: true
timezone: 'America/New_York'
